### ISSUE TITLE
docs(pt): review and update if possible the `guide/scaling-up/ssr.md`

### ISSUE THREAD

**Issue by nazarepiedady** [vuejs-translations/docs-pt#109]

**Comment by viniciusdeliz** [comment]
Please assign me this one

**Comment by nazarepiedady** [comment]
@viniciusdeliz, this task is yours. 😍

**Comment by viniciusdeliz** [comment]
@nazarepiedady Can you put me in the "Assignees" section of the issue? I'm not being able to do that kind of attribution anymore

**Comment by nazarepiedady** [comment]
@viniciusdeliz I will try to give you the powers of a moderator.
