### ISSUE TITLE
docs(pt): review and update if possible the `guide/scaling-up/state-management.md`

### ISSUE THREAD

**Issue by nazarepiedady** [vuejs-translations/docs-pt#110]
The aim of this issue is to review this content to find out how easy it is for Portuguese speakers to understand, regardless of their origin.

**Comment by viniciusdeliz** [comment]
@savionascimentodev gostaria de colaborar com a revisão desse arquivo?

**Comment by nazarepiedady** [comment]
@savionascimentodev, the task is yours. Just try not to forget that aims are the ease of reading and updating the content.

**Comment by savionascimentodev** [comment]
Ok @viniciusdeliz, @nazarepiedady, I'll do my best
