### ISSUE TITLE
docs(pt): review and update if possible the `guide/scaling-up/testing.md`

### ISSUE THREAD

**Issue by nazarepiedady** [vuejs-translations/docs-pt#111]
The aim of this issue is to review this content to find out how easy it is for Portuguese speakers to understand, regardless of their origin.

**Comment by nazarepiedady** [comment]
I am updating and reviewing this material.

**Comment by viniciusdeliz** [comment]
Can I do this one @nazarepiedady?

**Comment by nazarepiedady** [comment]
@viniciusdeliz, I am working on this, you need to discard the changes you have to focus on the issues I am creating now.

**Comment by viniciusdeliz** [comment]
I've sent the PR with the changes I had done anyway, better here than abandoned. Take it or leave it...
