### ISSUE TITLE
Hydration mismatch results in improper rendering

### ISSUE THREAD

**Issue by viniciusdeliz** [vuejs-translations/docs-pt#128]
![hydration-mismatch](https://github.com/vuejs-translations/docs-pt/assets/5748616/cb1e9381-a4df-45f3-87b0-c034d7deb13b)

That's also happening with some other pages atm

**Comment by nazarepiedady** [comment]
Yes, I saw this a few weeks ago, but I did not have enough time to debug it.

@viniciusdeliz, could you debug it?
