### ISSUE TITLE
docs(pt): review and update `guide/best-practices/security.md`

### ISSUE THREAD

**Issue by nazarepiedady** [vuejs-translations/docs-pt#141]

**Comment by savionascimentodev** [comment]
Hello gentlemen, could you assign this task to me?

**Comment by nazarepiedady** [comment]
@savionascimentodev, just do not forget to consult the #132 to know the rules we should follow while translating the files, by default we are using Brazilian dialect for 80% of the documentation and 20% is using words that are common to all different variants.
