### ISSUE TITLE
feat: implement `another-meaning` component

### ISSUE THREAD

**Issue by nazarepiedady** [vuejs-translations/docs-pt#148]
I like to find solutions, so I propose to code a component that will hold another meaning of a specific word that will be shown on a tool tip component when the word is hovered.

@viniciusdeliz, I do not like to leave problems without a proper solution, so what do you think about doing this task?

The idea is a component that will be used this way:

```vue
<another-meaning content="Renderizar">Interpretar</another-meaning>
```

And since the majority of consumers are Brazilians, we could do something like this:

```vue
<another-meaning content="Interpretar">Renderizar</another-meaning>
```

**Comment by nazarepiedady** [comment]
@savionascimentodev, what do you think about the idea?

**Comment by nazarepiedady** [comment]
@viniciusdeliz, what do you think about the idea?

Let's solve this problem together. ❤️

**Comment by savionascimentodev** [comment]
@nazarepiedady, Entendi a proposta e concordo totalmente em buscar soluções eficazes. A ideia de criar um componente para dar outro significado a uma palavra específica, como um toque de dica de ferramenta, parece ótima.

Quanto à diferença entre "interpretar" e "renderizar", acredito que a escolha de "renderizar" é mais apropriada para o contexto brasileiro. "Interpretar" pode ter diversas interpretações, e vale ressaltar que, especialmente no campo da programação, pode levar a equívocos, pois existem os conceitos de compiladores e interpretadores em linguagens de programação.

Com essa abordagem, acredito que não apenas poderemos aprimorar a experiência de tradução para o público brasileiro, mas também contribuir de maneira valiosa para outros usuários não brasileiros. Estamos no caminho certo para criar algo que beneficie a todos. Vamos seguir adiante com entusiasmo!

**Comment by nazarepiedady** [comment]
@savionascimentodev, não existe o termo `renderizar` como termo membro da língua Portuguesa, a dificuldade que muitos  brasileiros (porque não são todos) têm em entender é porque apenas conhecem o vocabulário brasileiro. Nós sabemos que existe maneiras de expressar certas assuntos sem recorrer a empréstimos de termos estrangeiros porque temos muita experiência com mais de um vocabulário, que diferente com a maioria dos brasileiros.

Eu analisarei esta ideia, porém se não funcionar como esperado, fecharei esta questão e adicionarei uma ligação que conduzirá a um bom dicionário da língua Portuguesa, que quiser aprender vai dar um jeito, que não quiser vai dar uma desculpa.

Nós aprendemos a forma que os brasileiros se comunicam, que é muito diferente da nossa, e muitos a adotam no informal. O Português brasileiro formal não é tão diferente do nosso Português corrente. Eu tenho vários livros da Novatec para provar, mas não entendo a razão das traduções comunitárias terem tão pouco rigor.

Nunca foi meu objetivo servir a maioria, apenas quem realmente quer usufruir dos benefícios de ter algum conteúdo em Português, eu não busco mudar as traduções feitas no Português do Brasil, ao contrário eu sigo atrás do que for necessário para entender o material, não custa nada para quem realmente quer aprender e deseja conhecimento.

Não sou de aceitar desculpas como razão da preguiça ou falta de vontade, quer ou não quer aprender?

"Não entendo", pegue o dicionário como também muitos fizeram.

**Comment by savionascimentodev** [comment]
Ok amigo faça do jeito que achar melhor o repositório é seu dei apenas uma ideia, não acontecera denovo.

https://www.dicio.com.br/renderizar/

https://pt.wikipedia.org/wiki/Renderiza%C3%A7%C3%A3o

https://dicionario.priberam.org/renderizar

https://www.infopedia.pt/dicionarios/lingua-portuguesa/renderizar

**Comment by viniciusdeliz** [comment]
https://ciberduvidas.iscte-iul.pt/consultorio/perguntas/o-uso-do-anglicismo-render-informatica/30536
Data: 12 de dezembro de 2011

**Comment by nazarepiedady** [comment]
@viniciusdeliz, também serve, tens uma solução para a não utilização de palavras oriundas do Inglês, o famoso estrangeirismo?

Eu sinceramente não quero ver termos como **template**, **string**, **CLI***, **link**, **array**, e muitos outros termos que se costuma deixar-se sem tradução, no meio do conteúdo em Português, e sabendo que as pessoas podem simplesmente aprender, não quero saber do argumento de que é comum usar-se esses termos em Inglês, eu quero uma documentação em Português, se não for conteúdo de código deve ser traduzido.

Uma vez que a **Vue.js** é uma abstração  ou estrutura, o artigo que refere-se a ela deve estar no feminino, o masculino fere a **naturalidade da linguagem** por exemplo: **O Vue.js é uma estrutura**, o género do primeiro artigo não condiz com o género das palavras que se seguem.

São as minhas preocupações, começaremos a retificação imediatamente, mas estrangeirismo não entra nesta documentação, apenas Português. Se é possível ter uma versão em Português, ainda que adaptada ou extensa, é versão em Português que deve ser usada.

Nós somos solucionadores de problemas, eu sei que encontraremos alguma solução.

**Comment by nazarepiedady** [comment]
@viniciusdeliz, também estou aberto a traduzir tudo para o Brasileiro **mas sem estrangeirismo**, porém **com estrangeirismo**  nada feito.

Eu acho que está minha última sugestão é a melhor de todas e a que dá menos trabalho, **tudo no Português do Brasil sem estrangeirismo**.
