### ISSUE TITLE
docs(pt): problem rendering codes

### ISSUE THREAD

**Issue by patrickmonteiro** [vuejs-translations/docs-pt#179]
I was recently analyzing the pt-br documentation, and I realized that it is the only one that is not correctly rendering the code snippets:

<img width="749" alt="Captura de Tela 2024-06-25 às 09 02 04" src="https://github.com/vuejs-translations/docs-pt/assets/13258255/a70f26ac-4e1d-4284-834a-7345bb47b06f">

<img width="733" alt="Captura de Tela 2024-06-25 às 09 02 17" src="https://github.com/vuejs-translations/docs-pt/assets/13258255/5c337592-d6dd-4526-8fa4-265c87f261b4">

All other documentation is rendered correctly:

<img width="736" alt="Captura de Tela 2024-06-25 às 09 03 00" src="https://github.com/vuejs-translations/docs-pt/assets/13258255/d7b574e7-bc2b-4762-a4d5-0e2a0415a730">

<img width="732" alt="Captura de Tela 2024-06-25 às 09 03 28" src="https://github.com/vuejs-translations/docs-pt/assets/13258255/33920e0b-ddd3-4182-b751-605a591a6cd2">

I quickly analyzed the MD files they seem to be written correctly, so it could be some configuration in parent files

**Comment by nazarepiedady** [comment]
@patrickmonteiro, I apologise for my delay in resolving this situation, but I believe I will resolve it later this week.

And thank you very much for reminding me, I have forgotten some things because of the rush and duties in other projects.
