### ISSUE TITLE
docs(pt): translate `style-guide/rules-strongly-recommended.md`

### ISSUE THREAD

**Issue by nazarepiedady** [vuejs-translations/docs-pt#47]
A tradução deste documento está sobre a responsabilidade do @nazarepiedady

**Comment by nazarepiedady** [comment]
Agora, a tradução deste documento está sobre a responsabilidade do @mumumilk.

@mumumilk atualize a tua bifurcação (conhecido como **fork**) local antes de começares a traduzir este documento.

Nós estamos a caminhar muito bem, teremos tudo terminado ainda antes de Dezembro, contando com a fase de revisão.

**Comment by viniciusdeliz** [comment]
@mumumilk please let me know if you're available to collaborate with the translation of this file

**Comment by nazarepiedady** [comment]
@viniciusdeliz do not worry so much, because it is possible that he is too occupied at this moment.
But if he does not respond in two weeks, we will need to go ahead without him.

**Comment by mumumilk** [comment]
yep im doing this one!

**Comment by nazarepiedady** [comment]
@viniciusdeliz, in case this file is not translated by the middle of the next month,
could you take it to translate it yourself?

**Comment by viniciusdeliz** [comment]
Working on this atm
