### ISSUE TITLE
docs(pt): replace the second singular pronoun with the first of plural.

### ISSUE THREAD

**Issue by nazarepiedady** [vuejs-translations/docs-pt#84]
@viniciusdeliz, I could see that you had problems updating the documentation, so I would like to ask you to do more important work. We know that the documentation is for all Portuguese speakers but since there is some use of the language that is not common for all speakers, I intend to replace words such as **Tu podes** with **Nós podemos**, and all second singular pronoun with the first plural pronoun.

You will create an issue for each file already translated, then we will review it together. And about the translation, let it be with me.

**Comment by viniciusdeliz** [comment]
Honestly this is the least priority at the moment. As I mentioned in the [another issue](https://github.com/nazarepiedady/vue3-docs-pt/issues/33), the current branch is severely outdated. Almost every file has changes and they can not be synched seamlessly with the original [vuejs/docs](https://github.com/vuejs/docs) as a source of truth.

**Comment by nazarepiedady** [comment]
@viniciusdeliz we already are at our new home, [vuejs-translations/docs-pt](https://github.com/vuejs-translations/docs-pt).
Now the only thing we need to do is wait for the signal to continue the development of the project.

**Comment by viniciusdeliz** [comment]
Now that the docs are already published, and having the time to review and think about this, I can say that it's actually a good suggestion, kudos! But I believe it won't cover all the scenarios unfortunately. The goal is quite summarized though: using any form of the second person will always sound very inadequate to the whole PT-BR audience (which I believe should be heavily considered since it's probably at least 3/4 of the total target users)

**Comment by nazarepiedady** [comment]
@viniciusdeliz I am refactoring and updating the documentation at the same time, I decided to use "Nós" as a translation adaptation for "You" in the majority of the time instead of using "Tu" where the verbs conjugation differs from Non-Brazillians to Brazilians.

I would like to invite you to read the content of the Tutorial and API section to see how they feel.

I am willing to make the necessary effort to provide the Portuguese documentation that our Brazilians colleagues can use too.

**Comment by nazarepiedady** [comment]
@viniciusdeliz, the pronoun "você" is more used in Brazil, but out of it (in others, Portuguese countries) are used "Tu" and the verb for this person is always used in plural, for example, "Tu estás bem", I am replacing this pronoun by "Nós" which conjugation is the same for all Portuguese variations.

See the Tutorial and API sections.

**Comment by viniciusdeliz** [comment]
Suggestion for future reviews, changes or replacements regarding proofreading and revision: limit the changes per page/article/item instead of doing a huge change/commit/PR that will modify diverse instances of different files.

**Comment by nazarepiedady** [comment]
@viniciusdeliz I make changes by document, is this what you are talking about?

If not could you explain more clearly?

**Comment by nazarepiedady** [comment]
@viniciusdeliz, I understand now, I am creating the issues for them now.

**Comment by nazarepiedady** [comment]
I am closing this issue since we already have some idea about what we need to do now.
